/*
 * File: leg_pos.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 03-Jul-2024 18:42:00
 */

/* Include Files */
#include "leg_pos.h"
#include <math.h>
#include "arm_math.h"
#include <stdio.h>
#include "main.h"
/* Function Declarations */
static float rt_atan2f_snf(float u0, float u1);

/* Function Definitions */
/*
 * Arguments    : float u0
 *                float u1
 * Return Type  : float
 */
static float rt_atan2f_snf(float u0, float u1)
{
  float y;
  if (u1 == 0.0F) {
    if (u0 > 0.0F) {
      y = PI / 2.0F;
    } else if (u0 < 0.0F) {
      y = -(PI / 2.0F);
    } else {
      y = 0.0F;
    }
  } else {
    y = atan2f(u0, u1);
  }

  return y;
}

/*
 * LEG_POS
 *     POS = LEG_POS(PHI1,PHI4)
 *
 * Arguments    : float phi1
 *                float phi4
 *                float pos[2]
 * Return Type  : void
 */
/**
 * @brief 根据电机角度计算足端位置（正运动学）
 *
 * @param phi1 电机1（髋关节）的角度
 * @param phi4 电机2（膝关节）的角度
 * @param pos 输出的足端位置（极坐标），pos[0]为腿长，pos[1]为腿部角度
 */
void leg_pos(float phi1, float phi4, float pos[2])
{
  float a;
  float b_a;
  float t10;
  float t12;
  float t13;
  float t2;
  float t3;
  float t4;
  float t5;
  float t6;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     27-Aug-2024 12:22:58 */
  /* 使用cosf和sinf计算三角函数值 */
  t2 = (float)cosf(phi1);
  t3 = (float)cosf(phi4);
  t4 = (float)sinf(phi1);
  t5 = (float)sinf(phi4);
  /* 运动学正解计算 */
  t6 = t2 * 0.155F;
  t10 = t4 * 0.155F;
  t12 = t4 * 0.0775F;
  t13 = t5 * 0.0775F;
  t5 = t10 - t5 * 0.155F;
  a = t12 - t13;
  b_a = (t3 * 0.155F - t6) + 0.11F;
  t4 = (t3 * 0.0775F - t2 * 0.0775F) + 0.055F;
  t5 = t5 * t5 + b_a * b_a;
  t4 = (float)atanf(1.0F / (t4 + t5) *
                   ((t13 - t12) + (float)sqrtf((a * a + t4 * t4) - t5 * t5))) *
       2.0F;
  t5 = t10 + (float)sinf(t4) / 4.0F;
  t4 = (t6 + (float)cosf(t4) / 4.0F) - 0.055F;
  /* 计算足端位置的模长（腿长）和角度（腿部姿态角）*/
  pos[0] = (float)sqrtf(t5 * t5 + t4 * t4);
  pos[1] = rt_atan2f_snf(t5, t4);

}

/*
 * File trailer for leg_pos.c
 *
 * [EOF]
 */
