/*
 * File: leg_spd.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 03-Jul-2024 18:44:01
 */

/* Include Files */
#include "leg_spd.h"
#include <math.h>
#include "arm_math.h"
/* Function Definitions */
/*
 * LEG_SPD
 *     SPD = LEG_SPD(DPHI1,DPHI4,PHI1,PHI4)
 *
 * Arguments    : float dphi1
 *                float dphi4
 *                float phi1
 *                float phi4
 *                float spd[2]
 * Return Type  : void
 */
void leg_spd(float dphi1, float dphi4, float phi1, float phi4, float spd[2])
{
  float t106;
  float t10_tmp;
  float t11;
  float t12;
  float t13;
  float t14_tmp;
  float t15;
  float t16;
  float t17;
  float t2;
  float t28;
  float t29;
  float t3;
  float t32;
  float t33;
  float t4;
  float t44;
  float t47;
  float t5;
  float t56;
  float t71;
  float t76;
  float t77_tmp;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     27-Aug-2024 12:23:00 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t10_tmp = t2 * 0.155F;
  t11 = t3 * 0.155F;
  t12 = t2 * 0.0775F;
  t13 = t3 * 0.0775F;
  t14_tmp = t4 * 0.155F;
  t15 = t5 * 0.155F;
  t16 = t4 * 0.0775F;
  t17 = t5 * 0.0775F;
  t28 = t14_tmp - t15;
  t29 = t16 - t17;
  t32 = (t11 - t10_tmp) + 0.11F;
  t33 = (t13 - t12) + 0.055F;
  t44 = t28 * t28 + t32 * t32;
  t47 = t2 * t28 * 0.31F + t4 * t32 * 0.31F;
  t3 = t3 * t28 * 0.31F + t5 * t32 * 0.31F;
  t28 = 1.0F / (t33 + t44);
  t32 = t28 * t28;
  t5 = sqrtf((t29 * t29 + t33 * t33) - t44 * t44);
  t56 = 1.0F / t5;
  t4 = (t17 - t16) + t5;
  t2 = atanf(t28 * t4) * 2.0F;
  t5 = cosf(t2);
  t71 = sinf(t2);
  t76 = 1.0F / (t32 * (t4 * t4) + 1.0F);
  t77_tmp = t5 / 4.0F;
  t106 =
      (t16 + t47) * t32 * t4 +
      t28 * (t12 -
             t56 * ((t10_tmp * t29 + t14_tmp * t33) - t44 * t47 * 2.0F) / 2.0F);
  t2 = (t17 + t3) * t32 * t4 +
       t28 * (t13 - t56 * ((t11 * t29 + t15 * t33) - t44 * t3 * 2.0F) / 2.0F);
  t12 = t14_tmp + t71 / 4.0F;
  t16 = (t10_tmp + t77_tmp) - 0.055F;
  t5 *= t76;
  t11 = t5 * t2;
  t32 = t71 * t76;
  t47 = t32 * t2;
  t2 = (-t10_tmp - t77_tmp) + 0.055F;
  t56 = t2 * t2;
  t28 = 1.0F / t2;
  t4 = t12 * t12;
  t2 = 1.0F / sqrtf(t4 + t16 * t16);
  t3 = 1.0F / (t4 + t56);
  t5 = t10_tmp - t5 * t106 / 2.0F;
  t4 = t14_tmp - t32 * t106 / 2.0F;
  spd[0] = dphi4 * t2 * (t12 * t11 - t16 * t47) / 2.0F +
           dphi1 * t2 * (t12 * t5 * 2.0F - t16 * t4 * 2.0F) / 2.0F;
  t2 = t12 * (1.0F / t56);
  spd[1] = -dphi1 * t56 * t3 * (t28 * t5 - t2 * t4) +
           dphi4 * t56 * t3 * (t28 * (0.0F - t11 / 2.0F) + t2 * (t47 / 2.0F));
}

/*
 * File trailer for leg_spd.c
 *
 * [EOF]
 */
